POST     http://localhost:4000/postProveedor
Content-Type: application/json


{
        "Codigo" : "700800",
        "Nombre" : "jenry",
        "Direccion" : "calle primera",
        "Numero" : "8092311699",
        "Rnc" : "26649783",
        "Correo" : "empresa@gmail.com",
        "Registro" : "henryfuerte560@gmail.com"
      
}